[project]
name = "autodoserank"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "matplotlib~=3.9.1",
    "numpy~=2.0.1",
    "pandas~=2.2.2",
    "scipy~=1.14.0",
]
